import 'package:flutter/material.dart';
import 'package:resep_makanan/DetailResep.dart';
import 'package:resep_makanan/model/penjelasan.dart';

class LayarUtama extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Resep Makanan"),
      ),
      body: ListView(
        children: PenjelasanList.map((place) {
          return FlatButton(
            onPressed: () {
              Navigator.push(context, MaterialPageRoute(builder: (context) {
                return DetailResep(place: place);
              }));
            },
            child: Card(
              color: Colors.green[100],
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Expanded(
                    flex: 1,
                    child: Image.asset(place.imageAsset),
                  ),
                  Expanded(
                    flex: 2,
                    child: Padding(
                      padding: const EdgeInsets.all(10.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.center,
                        mainAxisSize: MainAxisSize.min,
                        children: <Widget>[
                          Text(
                            place.name,
                            style: TextStyle(fontSize: 16.0),
                          ),
                          SizedBox(
                            height: 12,
                          ),
                        ],
                      ),
                    ),
                  )
                ],
              ),
            ),
          );
        }).toList(),
      ),
    );
  }
}

var PenjelasanList = [
  Penjelasan(
    name: "Rendang Daging Padang",
    description:
        "Salah satu resep masakan Indonesia yang selalu membuat ketagihan&nbsp adalah rendang Padang. Siapa yang tidak kenal dengan rendang daging yang satu ini, kita semua tentu sudah tahu betapa lezat dan harumnya masakan ini. Memasak rendang daging sebaiknya menggunakan daging sapi yang memiliki kualitas yang terbaik, dan pilihlah daging yang masih dalam keadaan segar. Mari kita coba resep masakan Indonesia yang sangat populer ini.",
    bahan: [
      "Rendang Daging Padang",
      "BAHAN :",
      "- 500 gram daging sapi potong kotak jadi 8 atau 10 bagian",
      "- 600 ml santan kental, dari satu setengah butir kelapa",
      "- 5 sdm minyak goreng",
      "- 300 ml air",
      "BUMBU :",
      "- 10 buah cabai merah iris",
      "- 6 butir bawah merah",
      "- 3 siung bawah putih",
      "- 3 cm kunyit",
      "- 3 cm jahe",
      "- 3 cm lengkuas",
      "- 1 sdm garam",
      "- 2 lembar daun kunyit",
      "- 1 batang serai",
      "- 2 butir asam kandis ",
      "CARA MEMBUAT : ",
      "1. Tumis bumbu hingga harum, masukkan daging, aduk hingga berubah warna.",
      "2. Masukkan daun kunyit, serai, dan asam kandis. Aduk perlahan.",
      "3. Masukkan air. Masak hingga air menyusut. Aduk perlahan sesekali.",
      "4. Masukkan santan, masak dengan api sedang.",
      "5. Biarkan hingga daging empuk, kuah kering, dan berminyak. Angkat, sajikan.",
    ],
    imageAsset: "images/rendang.jpg",
  ),
  Penjelasan(
    name: "Rawon",
    description:
        "Rawon adalah salah satu resep masakan Indonesia yang populer juga. Harum keluwaknya sangat menggoda selera. Rawon lebih nikmat jika sudah menginap, kalau hendak disajikan pagi hari untuk sarapan sebaiknya dimasak pada malam harinya.",
    bahan: [
      "Rawon",
      "BAHAN :",
      "- 500 gram daging sapi agak berlemak",
      "- 2 liter air",
      "- 3 batang serai, memarkan",
      "- 3 cm lengkuas, memarkan",
      "- 5 lembar daun jeruk",
      "- 2 lembar daun salam",
      "- 4 sdm minyak untuk menumis",
      "- 2 tangkai daun bawang, potong-potong",
      "BUMBU :",
      "- 5 butir bawang merah",
      "- 3 siung bawang putih",
      "- 2 butir kemiri",
      "- 1 sdt ketumbar",
      "- 2 cm jahe",
      "- 2 cm kunyit",
      "- 3 bh cabai merah (opsional)",
      "- 4 bh keluwak tua, kukus, ambil isinya",
      "- 2 sdt garam",
      "PELENGKAP :",
      "- Kerupuk udang",
      "- 100 gram tauge pendek",
      "- 4 butir telur asin",
      "- Sambal",
      "CARA MEMBUAT : ",
      "1. Masak daging dengan api kecil",
      "2. Masukkan daun salam, serai, lengkuas, dan daun jeruk sampai daging empuk dan matang.",
      "3. Angkat daging, lalu potong kecil-kecil.",
      "4. Saring rebusan air daging, sisihkan bersama irisan daging.",
      "5. Haluskan semua bumbu halus, tumis sampai berbau harum.",
      "6. Angkat, lalu masukkan ke dalam kaldu daging.",
      "7. Masak dengan api kecil sampai mendidih kembali.",
      "8. Cicipi, apakah rasanya sudah pas.",
      "9. Masukkan daun bawang yang sudah dipotong, didihkan sebentar.",
      "10. Tuang rawon kedalam mangkuk, taburkan tauge pendek di atasnya.",
      "11. Sajikan bersama nasi hangat, telur asin dan sambal.",
    ],
    imageAsset: "images/rawon.jpg",
  ),
  Penjelasan(
    name: "Sate Ayam Madura",
    description:
        "Sate memang mudah dibeli, tetapi mungkin Anda iseng ingin membuatnya sendiri di rumah. Cobalah resep masakan Indonesia khas Madura yang satu ini.",
    bahan: [
      "Sate Ayam Madura",
      "BAHAN :",
      "- 250 g fillet ayam, dipotong dadu, kemudian tusukan ke tusukan sate",
      "- 1 buah jeruk nipis yang telah iris",
      "- 100 ml minyak goreng",
      "- 3 butir bawang merah, diiris tipis",
      "- 5 sdm kecap manis",
      "- nasi putih atau bisa diganti lontong secukupnya",
      "BUMBU :",
      "- 3 butir bawang putih",
      "- 4 butir bawang merah",
      "- 100 g kacang tanah, digoreng",
      "- garam secukupnya",
      "- 150 ml air kaldu ayam",
      "- 2 sdm minyak goreng",
      "SAMBAL :",
      "- cabe merah kecil 15 buah",
      "- bawang putih 4 siung",
      "- garam secukupnya",
      "- minyak goreng secukupnya",
      "CARA MEMBUAT : ",
      "1. Pembuatan bumbu kacang,&nbsp; haluskan bawang putih, bawang merah, kacang tanah, garam, dan juga kemiri.&nbsp; Tumis bumbu kacang hingga tercium bau harum, kemudian masukkan air kaldu dan selanjutnya masak sampai mengental lalu angkat. Sisihkan.",
      "2. Selanjutnya , campurkan 2 sendok makan bumbu kacang dengan ditambah 2 sendok makan kecap manis, lalu celupkan sate, kemudian bakar hingga setengah matang. Angkat lalu gulingkan lagi dalam bumbu, terus&nbsp; bakar lagi hingga matang, angkat.",
      "3. Untuk sambal bawang,&nbsp; Tumis bawang putih sampai setengah matang lalu angkat. Selanjutnya campur bawang putih ditambah juga cabe merah kecil, dan garam, haluskan.",
    ],
    imageAsset: "images/sate.jpg",
  ),
  Penjelasan(
    name: "Tahu Atau Tempe Bacem",
    description:
        "Tahu tempe bacem biasanya disajikan dengan sayur asem, sambal dan nasi putih.&nbsp; Resep masakan Indonesia ini&nbsp; enak juga digunakan bumbunya untuk ayam, tetapi sebaiknya memasaknya terpisah. Kalau sedang terburu-buru bisa saja dimasak bersamaan, tetapi tahunya dimasukkan belakangan agar tidak terlalu lunak atau hancur.",
    bahan: [
      "Tahu Atau Tempe Bacem",
      "BAHAN :",
      "- 400 gram tempe/tahu, potong sesuai selera",
      "- 800 ml air kelapa",
      "- 100 gram gula merah, sisir",
      "- 2 sdm kecap manis",
      "- 1 lembar daun salam",
      "- 1 cm lengkuas, memarkan",
      "- ½ sdt garam",
      "- minyak untuk menggoreng",
      "BUMBU :",
      "- 6 butir bawang merah",
      "- 4 siung bawang putih",
      "- ½ sdm ketumbar",
      "- 3 batang serai, ambil putihnya",
      "CARA MEMBUAT : ",
      "1. Ungkep atau rebus tempe bersama air kelapa, gula merah, kecap manis, daun salam, lengkuas, garam, dan bumbu halus sampai matang dan meresap. Biarkan dingin.",
      "2. Panaskan minyak, goreng di atas api sedang hingga kecokelatan. Angkat, tiriskan dan hidangkan.",
    ],
    imageAsset: "images/tahu bacem.jpg",
  ),
  Penjelasan(
    name: "Soto Ayam",
    description:
        "Soto merupakan salah satu resep masakan Indonesia yang mempunyai banyak variasi,&nbsp; soto ayam, soto daging, soto babat, soto sulung, soto Betawi, soto mie dan masih banyak lagi. Variasi tersebut bisa berdasarkan bahan/isi, tambahan bumbu atau tempat di mana resep itu berasal. Resep yang kami pilih adalah resep soto ayam bening yang biasa dimasak sebagai masakan rumahan keluarga Indonesia.",
    bahan: [
      "Soto Ayam",
      "BAHAN :",
      "- 1/2 ekor ayam",
      "- 2 liter air",
      "- 250 gr tauge panjang, buang akarnya",
      "- 1 batang daun bawang, iris halus",
      "- 1 1/2 sdt garam",
      "- 1 sdt gula pasir",
      "- 3 lembar daun jeruk",
      "- 1 batang serai, digeprek",
      "- 2 ruas lengkuas, digeprek",
      "- 2 ruas jahe, digeprek",
      "BUMBU :",
      "- 1 sdt merica bulat",
      "- 8 butir bawangmerah",
      "- 4 siung bawang putih",
      "- 3 ruas kunyi",
      "PELENGKAP :",
      "- 2 batang seledri iris halus",
      "- 1 buah tomat, iris",
      "- bawang merah goreng",
      "- jeruk nipis, belah",
      "CARA MEMBUAT : ",
      "1. Rebus ayam hingga ayam empuk. Kecilkan apinya.",
      "2. Tumis bumbu halus, daun jeruk, serai, lengkuas, dan jahe hingga keluar aromanya. Angkat dan masukkan ke dalam air rebusan ayam. Aduk rata dan masak hingga mendidih.",
      "3. Tambahkan garam, gula pasir, kaldu bubuk, daun bawang, dan tauge. Aduk rata dan masak sebentar lalu angkat.",
      "4. Sajikan dalam mangkuk dan beri bahan pelengkap.",
    ],
    imageAsset: "images/soto.jpg",
  ),
  Penjelasan(
    name: "Sop Buntut",
    description:
        "Resep masakan Indonesia berikutnya adalah Sop Buntut.&nbsp; Menu yang sangat digemari banyak orang, tapi banyak yang mengeluhkan susah memasaknya, tidak bisa empuk, berlemak, dan bau.",
    bahan: [
      "Sop Buntut",
      "BAHAN :",
      "- 1 kg buntut sapi",
      "- 2 cm jahe, digeprek",
      "- 1 btg daun bawang, iris",
      "- 1 sdm, minyak goreng",
      "- 200 gr wortel, potong serong atau dadu",
      "- 250 gr kentang, potong dadu",
      "- Pala bubuk secukupnya",
      "- Air untuk merebus secukupnya",
      "BUMBU :",
      "- 6 bh bawang merah",
      "- 3 bh bawang putih",
      "- 1 sdt merica bulat",
      "PELENGKAP :",
      "- bawang merah goreng",
      "- tomat, potong dadu",
      "- daun bawang iris kasar",
      "CARA MEMBUAT : ",
      "1. Masukkan buntut dalam panci hingga terendam air, rebus di atas api sampai mendidih",
      "2. Buang buih yang terapung diatas dan air rebusan pertama buntut. Hal ini berguna agar kaldu tidak berbau.",
      "3. Panaskan minyak goreng, kemudian tumis bumbu halus",
      "4. Selanjutnya masukkan bubuk pala, jahe, daun bawang hingga harum",
      "5. Berikutnya masukan buntut dan beri air",
      "6. Rebus dalam panci tertutup dengan api kecil",
      "7. Rebus wortel dan kentang di panci terpisah hingga matang, kemudian tiriskan.",
      "8. Setelah buntut lunak,ambil buntutnya lalu saring kaldunya, kemudian masukan kembali buntut ke dalam kaldu yang sudah disaring.",
      "9. Didihkan buntut kembali dengan api kecil",
      "10. Letakkan wortel dan kentang ke dalam mangkuk kemudian tuangkan kaldu dan buntut, kemudian beri taburan&nbsp; pelengkapnya.",
    ],
    imageAsset: "images/sop buntut.jpg",
  ),
  Penjelasan(
    name: "Mie Goreng",
    description:
        "Mie goreng mungkin bukan masakan asli Indonesia, tapi sudah menjadi resep masakan Indonesia yang sangat populer dan disukai hampir semua masyarakat Indonesia mulai dari anak-anak sampai orang tua. Resep berikut mudah dan praktis, yuk dicoba.",
    bahan: [
      "Mie Goreng",
      "BAHAN :",
      "- 1 bungkus mie telor",
      "- Secukupnya udang",
      "- 5 butir bakso ikan",
      "- 2 buah wortel",
      "- 1 batang daun bawang",
      "- 4 siung bawang merah",
      "- 2 siung bawang putih",
      "- Secukupnya minyak goreng",
      "- 3 sendok teh minyak wijen (opsional)",
      "- 1 1/2 sendok teh lada bubuk",
      "- Kecap",
      "- Garam",
      "- Air/Kaldu Ayam",
      "CARA MEMBUAT : ",
      "1. Rebus mie telor hingga lunak tapi jangan terlalu lembek,&nbsp; angkat dan tiriskan.",
      "2. Iris wortel, bakso, dan daun bawang.",
      "3. Siapkan udang yg telah dikupas bersih",
      "4. Haluskan bawang merah dan bawang putih",
      "5. Tumis bumbu halus hingga harum, masukkan udang, bakso, wortel.",
      "6. Tambahkan minyak wijen kemudian masukkan air, garam, lada sedikit kecap manis dan terakhir masukkan mie beserta daun bawang aduk hingga meresap.",
      "7. Icip, tambahkan garam sesuai selera.",
      "8. Tuang ke dalam piring, Sajikan",
    ],
    imageAsset: "images/mie goreng.jpg",
  ),
  Penjelasan(
    name: "Nasi Goreng",
    description:
        "Nasi goreng adalah salah satu resep masakan Indonesia yang sangat populer.&nbsp; Biasa menjadi menu sarapan di rumah karena ada sisa nasi kemarin malam.&nbsp; Sering juga menjadi menu andalan makan malam ala kaki lima, bahkan menjadi salah satu menu favorit di restoran. Tahun 2014 kemarin nasi goreng menempati urutan pertama resep masakan Indonesia paling dicari di Google. Nasi goreng mempunyai banyak sekali versi, berikut salah satunya.",
    bahan: [
      "Nasi Goreng",
      "BAHAN :",
      "- 1 piring nasi putih",
      "- 2 buah sosis",
      "- kecap manis",
      "- kecap asin",
      "- garam",
      "- 2 sdm mixed vegetables",
      "- 1 sdm bawang merah goreng",
      "- mentega",
      "- 1 siung bawang putih",
      "- 1 butir telur",
      "- kaldu bubuk (opsional)",
      "PELENGKAP :",
      "- Kerupuk",
      "- Mentimun",
      "CARA MEMBUAT : ",
      "1. Geprek bawang putih lalu cincang dan potong sosis",
      "2. Kocok lepas telur",
      "3. Panaskan mentega hingga cair lalu masukkan telur, bawang putih dan sosis, tumis sebentar lalu masukkan nasi putih",
      "4. Tuang kecap manis dan kecap asin secukupnya lalu goreng lagi kemudian beri sedikit garam,&nbsp; dan satu sendok makan kaldu bubuk",
      "5. Cicipi sedikit, jika kurang rasa bisa ditambah sedikit garam lagi.",
      "6. Jika dirasa sudah pas, tuang nasi ke piring dan beri bawang goreng",
      "7. Sajikan selagi hangat.",
      "8. Tuang ke dalam piring, Sajikan",
    ],
    imageAsset: "images/nasi goreng.jpg",
  ),
];
